### ISSUE TITLE
Highlighted text annotations are not public... by default. I also can't make it public when I try.

### ISSUE THREAD

**Issue by KristinaFitz** [hypothesis/vision#214]
By default annotations made on highlighted text are not public.

I asked a friend to comment on an amendment as he is 'in the know'. He did as I asked, highlighted the text that was important and commented. I can not see his post.

When I highlight text and comment, I can not make my comment public. My REPLY to my own highlighted text can be made public, and shared. But not the original highlight and annotation..

Can this be fixed or is it this way for a reason?

If I simply click the annotate icon this is public. It is very important that specific lines can be uniquely addressed. Please let me know if or when highlighted text annotations will be public by default or enabled to make public.

I believe he and I are using the chrome extension.

**Comment by lenazun** [comment]
Hello @KristinaFitz 
Thanks for using Hypothesis! The application works like that by default. The reason is we have observed that most users who just highlight are often doing it for themselves, while users who add comments and annotate are often sharing them with others. 
You can make your highlights public by making a comment on them or adding a tag.  
I hope this clarifies the issue, otherwise let us know!

Lena

**Comment by KristinaFitz** [comment]
Thanks so much Lena! That makes good sense. I will try that out and let others know.
