### ISSUE TITLE
As a site owner, I want to keep annotations alive

### ISSUE THREAD

**Issue by teodorlu** [hypothesis/vision#222]
Thank you for a fantastic service. I haven't read all the documentation and issues -- so what I bring up may not be new to you. If that is the case, please say so!

As a site owner, I want to enable interaction with my readers through Hypothesis. I want to encourage Hypothesis as a platform for communication. For this, I want to be able to trust that discussions will stay alive.

**What happens if I, the site owner, move my documents, causing the URL to change? Can I notify Hypothesis of this somehow? Or will annotations for my documents forever be split among different URLs?**

Related points of attention:

- Should the right to move a discussion belong to a single individual? How can one prevent abuse from site owners that want to prevent discussions they don't like? Is it possible to provide a link, a suggestion in place of a forced move?
- How should the users interact with this information? Should they know that the site has moved?
- How can a site owner prompt users to use Hypothesis instead of providing a commentary field? Annotations and "discussions among the annotations" can live beyond a site if they are stored in a different place.
- Should the site owner be an archetype? Is the site owner a developer? Sometimes yes, sometimes perhaps not. His motivations may be different, providing information rather than building systems. The article author may publish his content on his web site.

**Comment by robertknight** [comment]
Hello @teodorlu 

Some very good questions! To keep things focused, I'll give a short answer to your initial question based on the status today and some thinking we've done in the past.

- Today, if a document moves from one URL to another then Hypothesis will not automatically learn about the change. Documents served from a particular URL can however declare their equivalence to other URLs by including appropriate metadata. Once our backend learns about the equivalence, it will serve up the same annotations regardless of which URL in a set of equivalent URLs is requested.
- Documents can declare persistent URL-independent identifiers (eg. DOIs) which the client will pick up from standard meta-tags and use for fetching annotations. This allows the same set of annotations to be surfaced when the user visits the same document at different URLs, even if no equivalences between those URLs have previously been established in our database.
- We like to re-use existing features of the web where appropriate, in keeping with our "mission" of enhancing the capabilities of the web. Once such approach to handling moved content would be to leverage redirects. The site owner establishes a redirect from the old to the new URL and Hypothesis provides an interface where a user (anyone) can submit a URL and our service will follow the redirect and establish an equivalence between the old and new URLs based on that. There are some challenges to deal with, such as what happens if the redirect is dynamic, but I think those are solvable.

**Comment by teodorlu** [comment]
Thanks, @robertknight, for the reply.

I like the metadata approach. Serve information that best describes the facts, then Hypothesis can interpret those in the best way possible. Clean separation between Hypothesis and content providers.

Up to you whether to close this issue or keep it open. My question has been answered.

**Comment by teodorlu** [comment]
Just came over your [Guidance for Publishers](https://web.hypothes.is/for-publishers/#embedding). Just what I wanted. Thanks a lot!

Shout out to [WikiWikiWeb](http://wiki.c2.com) which already has done this!

**Comment by ajpeddakotla** [comment]
closing in favor of https://github.com/hypothesis/product-backlog/issues/203
